Frontend:
  impl: BHO3
  clock_ratio: 8
  num_expected_insts: 800000000
  llc_capacity_per_core: 2MB
  llc_num_mshr_per_core: 16
  inst_window_depth: 128
  traces: 
    - 434.zeusmp
  
  Translation:
    impl: RandomTranslation 
    max_addr: 17179869

MemorySystem:
  impl: BHDRAMSystem
  clock_ratio: 3

  DRAM:
    impl: DDR5-VRR
    org:
      preset: DDR5_16Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: DDR5_3200AN 
    RFM:
      BRC: 2
    PRAC: true

  BHDRAMController:
    impl: PRACDRAMController
    BHScheduler:
      impl: PRACScheduler
    RefreshManager:
      impl: AllBank
      refresh_log_interval: 1  # 추가된 설정      
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
    plugins:
      - ControllerPlugin:
          impl: DPRAC
          abo_delay_acts: 4
          abo_recovery_refs: 4
          abo_act_ns: 180
          abo_threshold: 512
          add_thres: 8
          max_thres_rows: 6 
          debug: true
          trefi_reset: yes
          Extend: no
          serviceQ: no
          adaptive_prac: no
      - ControllerPlugin:
          commands_to_count:
          - ACT
          - PRE
          impl: CommandCounter
          path: ./sample.cout       

  AddrMapper:
    impl: RoBaRaCoCh_with_rit
